### PR TITLE
added Sandbox configurations

### PR DESCRIPTION
**Pull request by dwolff**
I've added the Sandbox configuration.

With this, you can also pass the "sandbox" as "True" or "False" (default) to initialize the PagSeguro instance.

I think that fixes the issue #21.

Great library, by the way. :)

### CODE REVIEW

**Comment by ellisonleao** [comment]
In terms of verbosity, isn't better to have just one `Config` class who can handle both sandbox and production environments?

**Comment by dwolff** [comment]
I've tried to do that, but I had problems with passing the parameter 
(sandbox=True or False) without a __init__ constructor to the Config object.

**Comment by ellisonleao** [comment]
we could add a `SANDBOX` class variable, getting its value with a `os.getenv` call, like

```
class Config(object):
      ...
      SANDBOX = os.environ.get('PAGSEGURO_SANDBOX', False)
```
in this way we can export the sandbox variable and just calling for the `app.config['SANDBOX']` when needed. What do you think @rochacbruno ?

**Comment by rochacbruno** [comment]
I do not like forcing the use of environment variable, we can just implement the first @dwolff  idea and create ``__init__`` method in Config class to decide which data to use.

I will take a look and propose a solution.

**Comment by arthurbarros** [comment]
@rochacbruno +1 about forcing env vars.

What about change the constructor of PagSeguro class and give the user the possibility to pass their own Config object ?

```python
class PagSeguro(object):
...
    def __init__(self, email, token, data=None, config=None):
        self.config = Config() if not config else config
...

my_config = MyOwnConfig()
pagseguro = Pagseguro(email='foo@bar', token='baz', config=my_config)

```

**Comment by rochacbruno** [comment]
:+1:  @arthurbarros

**Comment by rochacbruno** [comment]
Now it is possible to pass config objects, support added by @arthurbarros on #25, so now we only need to include SandBox config as an option in config module

**Comment by rochacbruno** [comment]
done in #32

**Pull request closed without merging**
