### PR TITLE
To python 3.7

### PR DESCRIPTION
**Pull request by MarcusMann**
The project has been updated to python 3.7 version.

This pr is referenced #60

### CODE REVIEW

**Comment by rochacbruno** [comment]
@mazulo @MarcusMann please send me your usernames of PyPI then I add you both as maintainers there.

**Comment by mazulo** [comment]
@rochacbruno here it is: `mazulo`

**Comment by MarcusMann** [comment]
@rochacbruno marcusmann

**Comment by MarcusMann** [comment]
Maybe the next time, you use Squash and Merge.
Thanks!

**Comment by mazulo** [comment]
I don't like the squash approach in that case. IMHO we just use it when we're working locally, but for PRs and stuffs it's better to maintain all the separated (atomic) commits intact, in order to better know where an specific feature was added.

**Pull request merged**
